name: CI Pipeline

on:
  push:
    branches:
      - main
      - developer

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Set permissions for Maven Wrapper
        run: chmod +x ./mvnw

      - name: Clear Maven Cache
        run: ./mvnw clean install

      - name: Run tests
        run: ./mvnw test